# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [20]:
import numpy as np
arr1 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
out_arr = np.vstack((arr1, arr2)) 
out_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [21]:
import numpy as np
arr1 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
out_arr = np.hstack((arr1, arr2)) 
out_arr

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [33]:
import numpy as np
arr=np.array([[0,1,2,3,4], [5,6,7,8,9]])
newarr = arr.flatten()
newarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [34]:
import numpy as np
arr=np.array([[0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14]])
newarr = arr.ravel()
newarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [43]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
newarr = arr.reshape(5,3)
newarr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [60]:
import numpy as np
x = np.random.rand(5,5)
print("Original Array:")
print(x)
y = np.square(x)
print(y)


Original Array:
[[0.47168413 0.26967349 0.6940876  0.63121396 0.5807152 ]
 [0.47181866 0.81701357 0.84265344 0.51363351 0.42193528]
 [0.01008527 0.88974462 0.35440371 0.69505414 0.0887956 ]
 [0.71140732 0.81323914 0.47490546 0.1137799  0.28697748]
 [0.54771944 0.74452482 0.26939224 0.33340017 0.70981978]]
[[2.22485919e-01 7.27237890e-02 4.81757600e-01 3.98431063e-01
  3.37230143e-01]
 [2.22612852e-01 6.67511172e-01 7.10064812e-01 2.63819382e-01
  1.78029380e-01]
 [1.01712571e-04 7.91645486e-01 1.25601992e-01 4.83100255e-01
  7.88465892e-03]
 [5.06100369e-01 6.61357902e-01 2.25535198e-01 1.29458646e-02
  8.23560756e-02]
 [2.99996589e-01 5.54317205e-01 7.25721767e-02 1.11155671e-01
  5.03844122e-01]]


## Question:8

### Create 5x6 an array and find the mean?

In [70]:
import numpy as np
a = np.reshape(np.arange(30), (5,6))
print(a)
print('Mean of Array:',np.mean(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean of Array: 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [71]:
import numpy as np
a = np.reshape(np.arange(30), (5,6))
print(a)
print('Standard Deviation of Array:',np.std(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Standard Deviation of Array: 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [72]:
import numpy as np
a = np.reshape(np.arange(30), (5,6))
print(a)
print('Median of Array:',np.median(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Median of Array: 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [73]:
import numpy as np
a = np.reshape(np.arange(30), (5,6))
print(a)
print('Transpose of Array:',np.transpose(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Transpose of Array: [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [75]:
import numpy as np 
n_array = np.array([[55, 25, 15,10], [30, 44, 2,20], [11, 45, 77,30],[34,32,30,31]]) 
print("Numpy Matrix is:") 
print(n_array) 
diag = np.diagonal(n_array) 
print("\nDiagonal elements are:") 
print(diag) 
print("\nSum of Diagonal elements is:") 
print(sum(diag)) 

Numpy Matrix is:
[[55 25 15 10]
 [30 44  2 20]
 [11 45 77 30]
 [34 32 30 31]]

Diagonal elements are:
[55 44 77 31]

Sum of Diagonal elements is:
207


## Question:13

### Find the determinant of the previous array in Q12?

In [80]:
import numpy as np 
n_array = np.array([[55, 25, 15,10], [30, 44, 2,20], [11, 45, 77,30],[34,32,30,31]]) 
print("Numpy Matrix is:") 
print(n_array)
print('Transpose of Array:',np.transpose(n_array))

Numpy Matrix is:
[[55 25 15 10]
 [30 44  2 20]
 [11 45 77 30]
 [34 32 30 31]]
Transpose of Array: [[55 30 11 34]
 [25 44 45 32]
 [15  2 77 30]
 [10 20 30 31]]


## Question:14

### Find the 5th and 95th percentile of an array?

In [83]:
import numpy as np
arr = [20, 2, 7, 1, 34]
print("arr : ", arr) 
print("5th percentile of arr : ", np.percentile(arr, 5))
print("95th percentile of arr : ",np.percentile(arr, 95))

arr :  [20, 2, 7, 1, 34]
5th percentile of arr :  1.2000000000000002
95th percentile of arr :  31.2


## Question:15

### How to find if a given array has any null values?

In [88]:
import numpy as np
     
b = [[1,2,3],[np.nan,np.nan,2]] 
arr = np.array(b)

print(arr)
print(np.isnan(arr))

x = np.isnan(arr)

#replacing NaN values with 0
arr[x] = 0
print("After replacing NaN values:")
arr
    

[[ 1.  2.  3.]
 [nan nan  2.]]
[[False False False]
 [ True  True False]]
After replacing NaN values:


array([[1., 2., 3.],
       [0., 0., 2.]])